# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Startpoint < Formula
  desc "A tui app to run and manage HTTP requests"
  homepage "https://github.com/susiteemu/startpoint"
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/susiteemu/startpoint/releases/download/v1.1.1/startpoint_Darwin_x86_64.tar.gz"
      sha256 "8d90875ef9296e3fcbc80a1c8778fe1ca294f7bc99f63e9e73e1dd7d08f4b748"

      def install
        bin.install "startpoint"
      end
    end
    on_arm do
      url "https://github.com/susiteemu/startpoint/releases/download/v1.1.1/startpoint_Darwin_arm64.tar.gz"
      sha256 "cabcf07ed1a290b008b5c9c6427a77a5234aeb9454048bf8cb27cebb8bbb6b00"

      def install
        bin.install "startpoint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/susiteemu/startpoint/releases/download/v1.1.1/startpoint_Linux_x86_64.tar.gz"
        sha256 "d3dae9eab6c05cbd47c72cea75cdd2f8c4f2651fff59da19bd02bafe647e47cb"

        def install
          bin.install "startpoint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/susiteemu/startpoint/releases/download/v1.1.1/startpoint_Linux_arm64.tar.gz"
        sha256 "594f39f8c9e2309c96515389501482f71e024410014b83bd097a61f6f0b6a83c"

        def install
          bin.install "startpoint"
        end
      end
    end
  end
end
